[Behat] Add additional scenarios for seeing lowest price on product show
Sylius/PriceHistoryPlugin pull request #12
Opened 2023-02-03 12:48 UTC by GSadee

2023-02-03 12:53 UTC, coldic3 commented on features/product/viewing_products/seeing_products_lowest_price_from_30_days_before_the_discount.feature
> +        Then I should see "$39.00" as thi
```suggestion
        Then I should see "$39.00" as this product's lowest price from 30 days before the discount
```

2023-02-03 13:18 UTC, Rafikooo requested changes

2023-02-03 13:18 UTC, Rafikooo commented on features/product/viewing_products/seeing_products_lowest_price_from_30_days_before_the_discount.feature
> +        And this product's discounted price changed to "$33.00"
```suggestion
        And this product's price was changed to "$33.00"
```

2023-02-03 14:13 UTC, Rafikooo approved these changes

2023-02-06 10:56 UTC, coldic3 approved these changes

2023-02-06 10:57 UTC, merged

2023-02-06 10:57 UTC, coldic3 commented
Thank you, @GSadee!